# Only for ubuntu / debian linux

---
- hosts: localhost
  become: yes
  become_method: sudo

  vars:
    kafka_home_dir: /kafka
    kafka_version: kafka_2.12-2.3.0
    kafka_archive_file: "{{ kafka_version }}.tgz"
    kafka_download_url: "https://www-us.apache.org/dist/kafka/2.3.0/{{ kafka_archive_file }}"
    kafka_bin_path: "{{ kafka_home_dir }}/{{ kafka_version }}/bin"
    
  tasks:
  - name: Update all packages
    apt:
      name: "*"
      state: latest
      update_cache: yes
      force_apt_get: true

  - name: Install Java (OpenJDK)
    apt:
      name: openjdk-11-jdk
      update_cache: yes
      install_recommends: yes
      state: present
      
  - name: Create kafka home directory
    file:
      path: "{{ kafka_home_dir }}"
      state: directory
      
  - name: Download kafka
    get_url:
      dest: "{{ kafka_home_dir }}/{{ kafka_archive_file }}"
      url: "{{ kafka_download_url }}"
      validate_certs: no
      timeout: 30
      
  - name: Extract kafka to kafka home directory
    unarchive:
      src: "{{ kafka_home_dir }}/{{ kafka_archive_file }}"
      dest: "{{ kafka_home_dir }}"
      
  - name: Add kafka bin to PATH environment variable (ubuntu)
    copy:
      content: 'PATH=$PATH:{{ kafka_bin_path }}'
      dest: /etc/profile.d/kafka-path.sh
